libcameraservice: HAX for depth sensor on ginkgo [2/2]
 * miui camera uses logical id 61 as depth sensor on portrait mode
   but oss libcam maps it to physical id 2 which is wrong, our physical
   id of depth sensor is 20 so we must hack it this way

[ghostrider-reborn 2021-10-26]
 * updated for android 12

[ghostrider-reborn 2022-09-23]
 * updated for android 13

[garry-rogov 2023-03-28]
 * updated for android 13 QPR2
 * fix error: too few arguments to function call, expected 4, have 3
                        physicalId, false, &mPhysicalDeviceInfoMap[physicalId]);

Change-Id: I57388d0e00fc21b99427e0c0b1ff9a39926b2243
Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Signed-off-by: garry-rogov <garry.rogov@gmail.com>